// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TAYF.Infrastructure.Data;

#nullable disable

namespace TAYF.Infrastructure.Migrations
{
    [DbContext(typeof(TayfDbContext))]
    [Migration("20260913142219_AddExpectedPowerToRepairVerification")]
    partial class AddExpectedPowerToRepairVerification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TAYF.Domain.Entities.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<decimal>("EnergyLossKwh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FinancialLoss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("InverterId")
                        .HasColumnType("int");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.Property<string>("Problem")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RecommendedAction")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RootCause")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InverterId");

                    b.HasIndex("PlantId");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("TAYF.Domain.Entities.AnalysisResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ActualEnergyKwh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ActualPowerKw")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AnomalyScore")
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("CauseProbabilities")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ConfidenceScore")
                        .HasColumnType("decimal(5,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Currency")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<decimal>("DeviationPct")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("EnergyLossKwh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EstimatedLoss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ExpectedEnergyKwh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ExpectedPowerKw")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("InverterId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAnomaly")
                        .HasColumnType("bit");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.Property<string>("PrimaryCause")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsAnomaly")
                        .HasDatabaseName("IX_AnalysisResult_IsAnomaly");

                    b.HasIndex("InverterId", "Timestamp")
                        .HasDatabaseName("IX_AnalysisResult_InverterId_Timestamp");

                    b.HasIndex("PlantId", "Timestamp")
                        .HasDatabaseName("IX_AnalysisResult_PlantId_Timestamp");

                    b.ToTable("AnalysisResults", (string)null);
                });

            modelBuilder.Entity("TAYF.Domain.Entities.Inverter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("InstallationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("MaxPowerKw")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.ToTable("Inverters", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InstallationDate = new DateTime(2023, 1, 31, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MaxPowerKw = 100m,
                            Model = "SUN2000-100KTL",
                            PlantId = 1,
                            SerialNumber = "INV-CAIRO-001"
                        },
                        new
                        {
                            Id = 2,
                            InstallationDate = new DateTime(2023, 1, 31, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MaxPowerKw = 100m,
                            Model = "SUN2000-100KTL",
                            PlantId = 1,
                            SerialNumber = "INV-CAIRO-002"
                        },
                        new
                        {
                            Id = 3,
                            InstallationDate = new DateTime(2023, 1, 31, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MaxPowerKw = 100m,
                            Model = "SUN2000-100KTL",
                            PlantId = 1,
                            SerialNumber = "INV-CAIRO-003"
                        },
                        new
                        {
                            Id = 4,
                            InstallationDate = new DateTime(2023, 1, 31, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MaxPowerKw = 100m,
                            Model = "SUN2000-100KTL",
                            PlantId = 1,
                            SerialNumber = "INV-CAIRO-004"
                        },
                        new
                        {
                            Id = 5,
                            InstallationDate = new DateTime(2023, 1, 31, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MaxPowerKw = 100m,
                            Model = "SUN2000-100KTL",
                            PlantId = 1,
                            SerialNumber = "INV-CAIRO-005"
                        });
                });

            modelBuilder.Entity("TAYF.Domain.Entities.MaintenanceAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActionType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("InverterId")
                        .HasColumnType("int");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InverterId");

                    b.HasIndex("PlantId");

                    b.ToTable("MaintenanceActions", (string)null);
                });

            modelBuilder.Entity("TAYF.Domain.Entities.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CapacityKw")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Currency")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("InstallationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("TariffRate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("TariffType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Plants", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CapacityKw = 500m,
                            Currency = 1,
                            InstallationDate = new DateTime(2023, 1, 14, 22, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Location = "Cairo, Egypt",
                            Name = "Solar Plant A - Cairo",
                            TariffRate = 1.25m,
                            TariffType = 1
                        });
                });

            modelBuilder.Entity("TAYF.Domain.Entities.RepairVerification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ExpectedPowerKw")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int?>("InverterId")
                        .HasColumnType("int");

                    b.Property<bool>("IsStable")
                        .HasColumnType("bit");

                    b.Property<int>("MaintenanceActionId")
                        .HasColumnType("int");

                    b.Property<decimal>("PerformanceAfter")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PerformanceBefore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("RecoveryPct")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("Verified")
                        .HasColumnType("bit");

                    b.Property<DateTime>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InverterId");

                    b.HasIndex("MaintenanceActionId");

                    b.ToTable("RepairVerifications", (string)null);
                });

            modelBuilder.Entity("TAYF.Domain.Entities.Tariff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Currency")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.ToTable("Tariffs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Currency = 1,
                            PlantId = 1,
                            Rate = 1.25m,
                            Type = 1
                        });
                });

            modelBuilder.Entity("TAYF.Domain.Entities.Telemetry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AcPowerKw")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmbientTemperature")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("DailyYield")
                        .HasColumnType("int");

                    b.Property<decimal>("DcPowerKw")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("InverterId")
                        .HasColumnType("int");

                    b.Property<int>("Irradiance")
                        .HasColumnType("int");

                    b.Property<decimal>("ModuleTemperature")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<long>("TotalYield")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("InverterId", "Timestamp")
                        .HasDatabaseName("IX_Telemetry_InverterId_Timestamp");

                    b.HasIndex("PlantId", "Timestamp")
                        .HasDatabaseName("IX_Telemetry_PlantId_Timestamp");

                    b.ToTable("Telemetry", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AcPowerKw = 0.03m,
                            AmbientTemperature = 22m,
                            DailyYield = 164,
                            DcPowerKw = 0m,
                            InverterId = 1,
                            Irradiance = 0,
                            ModuleTemperature = 22m,
                            PlantId = 1,
                            Timestamp = new DateTime(2026, 9, 4, 19, 19, 35, 646, DateTimeKind.Utc).AddTicks(6110),
                            TotalYield = 1000L
                        },
                        new
                        {
                            Id = 2,
                            AcPowerKw = 0.1m,
                            AmbientTemperature = 21m,
                            DailyYield = 624,
                            DcPowerKw = 0m,
                            InverterId = 2,
                            Irradiance = 49,
                            ModuleTemperature = 22.22m,
                            PlantId = 1,
                            Timestamp = new DateTime(2026, 9, 4, 19, 19, 35, 646, DateTimeKind.Utc).AddTicks(6110),
                            TotalYield = 2000L
                        },
                        new
                        {
                            Id = 3,
                            AcPowerKw = 2.85m,
                            AmbientTemperature = 19m,
                            DailyYield = 17098,
                            DcPowerKw = 0m,
                            InverterId = 3,
                            Irradiance = 0,
                            ModuleTemperature = 19m,
                            PlantId = 1,
                            Timestamp = new DateTime(2026, 9, 4, 19, 19, 35, 646, DateTimeKind.Utc).AddTicks(6110),
                            TotalYield = 3000L
                        },
                        new
                        {
                            Id = 4,
                            AcPowerKw = 0m,
                            AmbientTemperature = 21m,
                            DailyYield = 0,
                            DcPowerKw = 1.62m,
                            InverterId = 4,
                            Irradiance = 0,
                            ModuleTemperature = 21m,
                            PlantId = 1,
                            Timestamp = new DateTime(2026, 9, 4, 19, 19, 35, 646, DateTimeKind.Utc).AddTicks(6110),
                            TotalYield = 4000L
                        },
                        new
                        {
                            Id = 5,
                            AcPowerKw = 2.95m,
                            AmbientTemperature = 17m,
                            DailyYield = 17687,
                            DcPowerKw = 0m,
                            InverterId = 5,
                            Irradiance = 0,
                            ModuleTemperature = 17m,
                            PlantId = 1,
                            Timestamp = new DateTime(2026, 9, 4, 19, 19, 35, 646, DateTimeKind.Utc).AddTicks(6110),
                            TotalYield = 5000L
                        });
                });

            modelBuilder.Entity("TAYF.Domain.Entities.TelemetryProcessingCheckpoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InverterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastProcessedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("InverterId")
                        .IsUnique();

                    b.ToTable("TelemetryProcessingCheckpoints", (string)null);
                });

            modelBuilder.Entity("TAYF.Domain.Entities.Alert", b =>
                {
                    b.HasOne("TAYF.Domain.Entities.Inverter", "Inverter")
                        .WithMany("Alerts")
                        .HasForeignKey("InverterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TAYF.Domain.Entities.Plant", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inverter");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("TAYF.Domain.Entities.AnalysisResult", b =>
                {
                    b.HasOne("TAYF.Domain.Entities.Inverter", "Inverter")
                        .WithMany("AnalysisResults")
                        .HasForeignKey("InverterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TAYF.Domain.Entities.Plant", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Inverter");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("TAYF.Domain.Entities.Inverter", b =>
                {
                    b.HasOne("TAYF.Domain.Entities.Plant", "Plant")
                        .WithMany("Inverters")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("TAYF.Domain.Entities.MaintenanceAction", b =>
                {
                    b.HasOne("TAYF.Domain.Entities.Inverter", "Inverter")
                        .WithMany("MaintenanceActions")
                        .HasForeignKey("InverterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TAYF.Domain.Entities.Plant", "Plant")
                        .WithMany("MaintenanceActions")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Inverter");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("TAYF.Domain.Entities.RepairVerification", b =>
                {
                    b.HasOne("TAYF.Domain.Entities.Inverter", null)
                        .WithMany("RepairVerifications")
                        .HasForeignKey("InverterId");

                    b.HasOne("TAYF.Domain.Entities.MaintenanceAction", "MaintenanceAction")
                        .WithMany("RepairVerifications")
                        .HasForeignKey("MaintenanceActionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MaintenanceAction");
                });

            modelBuilder.Entity("TAYF.Domain.Entities.Tariff", b =>
                {
                    b.HasOne("TAYF.Domain.Entities.Plant", "Plant")
                        .WithMany("Tariffs")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("TAYF.Domain.Entities.Telemetry", b =>
                {
                    b.HasOne("TAYF.Domain.Entities.Inverter", "Inverter")
                        .WithMany("TelemetryRecords")
                        .HasForeignKey("InverterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TAYF.Domain.Entities.Plant", "Plant")
                        .WithMany("TelemetryRecords")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Inverter");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("TAYF.Domain.Entities.TelemetryProcessingCheckpoint", b =>
                {
                    b.HasOne("TAYF.Domain.Entities.Inverter", "Inverter")
                        .WithMany()
                        .HasForeignKey("InverterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Inverter");
                });

            modelBuilder.Entity("TAYF.Domain.Entities.Inverter", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("AnalysisResults");

                    b.Navigation("MaintenanceActions");

                    b.Navigation("RepairVerifications");

                    b.Navigation("TelemetryRecords");
                });

            modelBuilder.Entity("TAYF.Domain.Entities.MaintenanceAction", b =>
                {
                    b.Navigation("RepairVerifications");
                });

            modelBuilder.Entity("TAYF.Domain.Entities.Plant", b =>
                {
                    b.Navigation("Inverters");

                    b.Navigation("MaintenanceActions");

                    b.Navigation("Tariffs");

                    b.Navigation("TelemetryRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
